apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: gar-api
  name: gar-api
spec:
  type: NodePort
  ports:
  - name: headless
    port: 8010
  selector:
    io.kompose.service: gar-api
status:
  loadBalancer: {}
