apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.4.0 (c7964e7)
  creationTimestamp: null
  labels:
    io.kompose.service: gar-api
  name: gar-api
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: gar-api
    spec:
      containers:
      - args:
        - --spring.profiles.active=prod
        - --prod.database.url=jdbc:postgresql://egar.chmjeqipapmr.eu-west-2.rds.amazonaws.com/egardb
        - --prod.database.username=$(DB_USER)
        - --prod.database.password=$(DB_PASS)
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: egar-secret
                key: dbuser
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: egar-secret
                key: dbpass
        image: pipe.egarteam.co.uk/egar-gar-api:$GAR_API_VER
        name: gar-api
        livenessProbe:
          initialDelaySeconds: 90
          periodSeconds: 30
          httpGet:
            path: /healthz
            port: 8084
        resources: {}
      - args:
        - --discovery-url=http://auth.egarteam.co.uk/auth/realms/egar
        - --client-id=$(CLIENT_ID)
        - --client-secret=$(CLIENT_SECRET)
        - --listen=0.0.0.0:8010
        - --encryption-key=$(ENCRYPT_KEY)
        - --upstream-url=http://localhost:8084
        - --resources=uri=/api/*|roles=uma_authorization
        - --secure-cookie=false
        - --no-redirects=true
        - --upstream-response-header-timeout=50s
        - --upstream-timeout=50s
        - --upstream-keepalive-timeout=50s
        - --upstream-expect-continue-timeout=50s
        env:
          - name: CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: egar-secret
                key: clientid
          - name: CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: egar-secret
                key: clientsecret
          - name: ENCRYPT_KEY
            valueFrom:
              secretKeyRef:
                name: egar-secret
                key: enckey
        image: quay.io/gambol99/keycloak-proxy
        name: gar-api-proxy
        resources: {}
      restartPolicy: Always
status: {}
