apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: gar-api
  name: gar-api
spec:
  ports:
  - port: 8011
    protocol: TCP
  selector:
    io.kompose.service: gar-api
status:
  loadBalancer: {}
